version: '3'

volumes:
  mysql_data: {}
  mysql_backup: {}

services:
  mysql:
    image: mysql:5.6
    volumes:
      - M:\mysql_data_5.6:/var/lib/mysql
      - M:\mysql_config:/etc/mysql/conf.d
    env_file: .env
    ports:
      - 33066:3306
    command: mysqld -v --explicit_defaults_for_timestamp=1

  teamcity-server:
    image: jetbrains/teamcity-server
    volumes:
      - M:\teamcity_server\data\:/data/teamcity_server/datadir
      - M:\teamcity_server\logs\:/opt/teamcity/logs
    ports:
      - 8111:8111
    depends_on:
      - mysql
    env_file: .env

  teamcity-agent:
    build: ./docker/agents/phinx-nexus
    image: mvcaaa/tcagent-nexus
    env_file: .env-agent
    depends_on:
      - teamcity-server
      - mysql
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512M
