version: '2'

volumes:
  mysql_data: {}
  mysql_backup: {}

services:
  mysql:
    image: mysql
    volumes:
      - M:\mysql_data:/var/lib/mysql
#      - M:\mysql_config:/etc/mysql/conf.d
    env_file: .env
    ports:
      - 33066:3306
    restart: always

  teamcity-server:
    image: jetbrains/teamcity-server
    volumes:
      - M:\teamcity_server\data\:/data/teamcity_server/datadir
      - M:\teamcity_server\logs\:/opt/teamcity/logs
    ports:
      - 8111:8111
    depends_on:
      - mysql
    env_file: .env
    restart: always
    command: mysqld --sql-mode=MYSQL40

  teamcity-agent:
    build: ./docker/agents/phinx-nexus
    env_file: .env-agent
    restart: always
    depends_on:
      - teamcity-server
      - mysql