<?php

// User Default. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('USER_DEFAULT_ADMIN', 1);
define('USER_DEFAULT_DEVICE', 3);
define('USER_DEFAULT_GUEST', 4);

// Event Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('ET_LOG', 1);
define('ET_INSPECTION', 2);
define('ET_SALE', 3);
define('ET_PAYMENT', 4);
define('ET_ISSUING', 5);
define('ET_LOADING', 6);
define('ET_CHARGING', 7);
define('ET_VALIDATION', 8);
define('ET_ACCESS', 9);
define('ET_REVERSE_SALE', 10);
define('ET_RECEIPT', 11);
define('ET_SHIFT', 12);
define('ET_END_SHIFT', 13);
define('ET_TRANSFER_ACCESS_RIGHT', 14);
define('ET_LOCKER', 15);
define('ET_PRODUCT_EXTENSION', 16);
define('ET_ALARM', 17);
define('ET_EDIT', 18);
define('ET_INVENTORY', 19);
define('ET_MESSAGE', 20);
define('ET_TOKEN_ATTACH', 21);
define('ET_TOKEN_DETACH', 22);
define('ET_TRANSFER_RESERVATION', 23);
define('ET_IDENTITY_CHECK', 24);

// Edit Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('EDIT_NEW', 1);
define('EDIT_EDIT', 2);
define('EDIT_DELETE', 3);
define('EDIT_ADD_RELATION', 4);
define('EDIT_DELETE_RELATION', 5);
define('EDIT_UPDATE_RELATION', 6);

// Inventory Event Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('INVENTORY_ADD', 1);
define('INVENTORY_CORRECTION', 2);
define('INVENTORY_SALE', 3);
define('INVENTORY_OWN_USE', 4);
define('INVENTORY_MOVE', 5);
define('INVENTORY_LOST', 6);

// Access Right Status. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('AR_INVALID', 'invalid');
define('AR_CHARGEABLE', 'chargeable');
define('AR_VALIDABLE', 'validable');
define('AR_INSPECTABLE', 'inspectable');
define('AR_NOT_YET', 'not_yet');

// Token Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('TOKEN_MIFARE_CARD', 1);
define('TOKEN_MIFARE_KEYFOB', 2);
define('TOKEN_BARCODE', 3);
define('TOKEN_PIN', 4);
define('TOKEN_MOBILE', 5);
define('TOKEN_MICROLOG', 6);
define('TOKEN_EPC', 7);
define('TOKEN_HID', 8);
define('TOKEN_NT', 9);
define('TOKEN_EM', 10);
define('TOKEN_ICODE', 11);

// Token Prefix. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('TOKEN_PRE_MIFARE_CARD', 'mf_');
define('TOKEN_PRE_MIFARE_KEYFOB', 'mf_');
define('TOKEN_PRE_BARCODE', 'bc_');
define('TOKEN_PRE_PIN', 'pin_');
define('TOKEN_PRE_MOBILE', 'mt_');
define('TOKEN_PRE_MICROLOG', 'ml_');
define('TOKEN_PRE_EPC', 'epc_');
define('TOKEN_PRE_HID', 'hid_');
define('TOKEN_PRE_NT', 'nt_');
define('TOKEN_PRE_EM', 'em_');
define('TOKEN_PRE_ICODE', 'ic_');

// Module. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('NM_MAIN', 1);
define('NM_EN_AGREEMENTS', 2);
define('NM_EN_CUSTOMERS', 3);
define('NM_EN_RESERVATIONS', 4);
define('NM_EN_PAYMENTS', 5);
define('NM_EN_ACCESS_CONTROL', 6);
define('NM_EN_LOCKERS', 7);
define('NM_EN_CRM', 8);
define('NM_EN_SALESPOINT', 9);
define('NM_EN_ANALYTICS', 10);
define('NM_EN_TA', 11);
define('NM_EN_OFFLINE', 12);
define('NM_EN_ACS_CONTROL_PANEL', 13);
define('NM_EN_PRODUCTS', 14);
define('NM_EN_HELP', 15);
define('NM_EN_WEBSHOP', 16);
define('NM_EN_BALANCE', 17);
define('NM_EN_DMS', 18);
define('NM_EN_SUBSCRIPTIONS', 19);
define('NM_EN_SST', 20);
define('NM_EN_GOLDCARD_SERVER', 100);
define('NM_EN_GOLDCARD_CLIENT', 101);
define('NM_EN_INVENTORY', 102);
define('NM_EN_SMS', 103);
define('NM_EN_CTA', 104);
define('NM_EN_STATION', 107);
define('NM_SMARTUM_INTEGRATION', 24);
define('NM_WINTIME_INTEGRATION', 25);
define('NM_TIKON_INTEGRATION', 26);
define('NM_LIPPUPISTE_INTEGRATION', 27);
define('NM_WINPOS_INTEGRATION', 28);
define('NM_ALDATA_INTEGRATION', 29);
define('NM_FIDELIX_INTEGRATION', 30);
define('NM_NEXGOLF_INTEGRATION', 31);
define('NM_MICROFLEX_INTEGRATION', 32);
define('NM_EFINA_INTEGRATION', 33);
define('NM_GOOGLE_MAPS_INTEGRATION', 34);
define('NM_SAP_EXPORT', 35);
define('NM_VISMA_EXPORT', 36);
define('NM_NETVISOR_EXPORT', 37);
define('NM_PROE_ACCOUNTING_INTEGRATION', 38);
define('NM_PROE_INVOICE_INTEGRATION', 39);
define('NM_MOBILE_CUSTOMER_SERVICE', 40);
define('NM_TILAAJAVASTUU_INTEGRATION', 41);
define('NM_EXCEL_EXPORT', 42);
define('NM_AURINKOMATKAT_SAP', 43);
define('NM_GIFTCARD', 44);
define('NM_VESILIIKUNTAKORTTI', 45);
define('NM_SALESFORCE_INTEGRATION', 46);
define('NM_GOLFLIITTO_INTEGRATION', 47);
define('NM_ESPOO_ACCOUNTING_INTEGRATION', 48);
define('NM_POLAR_INTEGRATION', 49);
define('NM_HSL_INTEGRATION', 50);
define('NM_FK_VIITEMAKSUT_INTEGRATION', 51);
define('NM_COMMUNITY_INTEGRATION', 52);
define('NM_SMARTSHIP_INTEGRATION', 53);
define('NM_ID06_INTEGRATION', 54);
define('NM_HMS_INTEGRATION', 55);
define('NM_RAMISMART_INVENTORY_SERVICE', 56);
define('NM_SIERRA_INTEGRATION', 57);
define('NM_LEMONSOFT_ACCOUNTING_INTEGRATION', 58);
define('NM_LEMONSOFT_INVOICE_INTEGRATION', 59);
define('NM_E1_INTEGRATION', 60);
define('NM_HELSINKI_ASIOINTI_INTEGRATION', 61);
define('NM_TALPA_SAP_INVOICE_INTEGRATION', 62);
define('NM_PAYMENT_HIGHWAY_INTEGRATION', 63);
define('NM_VTJ_INTEGRATION', 64);

// User Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('UT_ADMINISTRATOR', 1);
define('UT_SALES_PERSON', 2);
define('UT_DRIVER', 3);
define('UT_DEVICE_DAEMON', 4);
define('UT_GUEST', 5);
define('UT_CUSTOMER', 6);
define('UT_MANAGER', 7);
define('UT_EXTERNAL', 8);
define('UT_INSTRUCTOR', 9);
define('UT_ACCESS_MANAGER', 10);
define('UT_EMPLOYEE', 11);
define('UT_TA_MANAGER', 12);
define('UT_EMPLOYER', 13);
define('UT_SERVICE_PROVIDER', 14);
define('UT_RESERVATION_MANAGER', 15);
define('UT_EXTERNAL_SALES_PERSON', 16);
define('UT_ACCOUNTANT', 17);
define('UT_LOCKER_SERVICE_DESK', 18);

// Device Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('DEVICE_SERVER', 1);
define('DEVICE_SALES_POINT', 2);
define('DEVICE_TURNSTILE', 3);
define('DEVICE_DOOR', 4);
define('DEVICE_VIRTUAL_ACS', 5);
define('DEVICE___UNUSED', 6);
define('DEVICE_EXTERNAL', 7);
define('DEVICE_SST', 8);
define('DEVICE_MOBILE', 9);
define('DEVICE_VIRTUAL_POS', 10);
define('DEVICE_MOBILE_POS', 11);

// Access Point Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('APT_TURNSTILE', 1);
define('APT_DOOR_WITH_PINPAD', 2);
define('APT_DOOR_WITHOUT_PINPAD', 3);
define('APT_TURNSTILE_WITH_SST', 4);
define('APT_WITH_SST', 5);

// Day Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('DAY_WORKDAY', 8);
define('DAY_WEEKEND', 9);
define('DAY_HOLIDAY', 10);
define('DAY_ANY_DAY', 11);

// Fare Product Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('FPT_NORMAL', 1);
define('FPT_CARD_PRODUCT', 2);
define('FPT_PRODUCT_WITH_VALIDATION', 3);
define('FPT_CARD_DEPOSIT', 4);
define('FPT_AGREEMENT_BALANCE', 5);
define('FPT_DEPOSIT', 6);
define('FPT_BUNDLE', 7);
define('FPT_LOAD_BALANCE', 8);
define('FPT_DISCOUNT', 9);
define('FPT_INVOICE_PAYMENT', 10);

// Customer Group. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('CG_ADULT', 1);
define('CG_STUDENT', 2);
define('CG_SENIOR', 3);
define('CG_CHILD', 4);

// Invoice Status. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('INVOICE_NEW', 1);
define('INVOICE_APPROVED', 2);
define('INVOICE_SENT', 3);
define('INVOICE_PAID', 4);
define('INVOICE_CANCELLED', 5);
define('INVOICE_IN_DEBT_COLLECTION', 6);

// Invoice Payment Source. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('INVOICE_PAYMENT_BANK', 1);
define('INVOICE_PAYMENT_POS', 2);
define('INVOICE_PAYMENT_NETVISOR', 3);
define('INVOICE_PAYMENT_NEXUS', 4);

// Payment Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('PT_CASH', 1);
define('PT_CARD', 2);
define('PT_INVOICE', 3);
define('PT_COUPON', 4);
define('PT_OBLIGATION', 5);
define('PT_EXTERNAL', 6);
define('PT_ROUNDING', 7);
define('PT_ONLINE', 8);
define('PT_SMARTUM_CARD', 9);
define('PT_PALVELUKASSA', 10);
define('PT_AGREEMENT_BALANCE', 11);
define('PT_WINPOS', 12);
define('PT_BALANCE', 13);

// Payment Class. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('PC_CASH', 1);
define('PC_CARD', 2);
define('PC_INVOICE', 3);
define('PC_COUPON', 4);
define('PC_OBLIGATION', 5);
define('PC_EXTERNAL', 6);
define('PC_ROUNDING', 7);
define('PC_ONLINE', 8);
define('PC_SMARTUM_CARD', 9);
define('PC_PALVELUKASSA', 10);
define('PC_AGREEMENT_BALANCE', 11);
define('PC_WINPOS', 12);
define('PC_BALANCE', 13);
define('PC_CASH_EXTRA', 14);
define('PC_CASH_MISSING', 15);
define('PC_DISCOUNT', 16);

// Price Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('PRICE_FIXED_PRICE', 1);
define('PRICE_PROMPT_ALWAYS', 2);
define('PRICE_PROMPT_OPTIONALLY', 3);
define('PRICE_TIME_SLOT_PRICE', 4);
define('PRICE_NEGATIVE_PRICE', 5);

// Access Mode. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('APM_CLOSED', 1);
define('APM_ACCESS_RIGHT', 2);
define('APM_ACCESS_RIGHT_AND_PIN', 3);
define('APM_BUTTON', 4);
define('APM_ALWAYS_OPEN', 5);
define('APM_NO_BARRIER', 6);
define('APM_PIN', 7);
define('APM_UNCONTROLLED', 8);
define('APM_SELECT', 9);

// Ta Status. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('TA_WORK', 1);
define('TA_OUT', 2);
define('TA_LUNCH', 3);
define('TA_SICK_LEAVE', 4);
define('TA_VACATION', 5);
define('TA_BUSINESS_TRIP', 6);
define('TA_HOLIDAY', 7);
define('TA_WEEKEND', 8);
define('TA_WORK_OUT', 9);
define('TA_SMOKING', 10);
define('TA_OVERTIME', 11);
define('TA_LUNCH_IN', 12);
define('TA_IN_EARLIER', 13);
define('TA_TOMORROW', 14);
define('TA_PAID_LEAVE', 15);

// Ta Time Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('TATT_TOTAL', 1);
define('TATT_DAILY_EXTRA_WORK', 2);
define('TATT_DAILY_OVERTIME_1', 3);
define('TATT_DAILY_OVERTIME_2', 4);
define('TATT_WEEKLY_EXTRA_TIME', 5);
define('TATT_WEEKLY_OVERTIME_1', 6);
define('TATT_WEEKLY_OVERTIME_2', 7);
define('TATT_HOLIDAY_WORK', 8);
define('TATT_REGULAR', 9);
define('TATT_FLEXIBLE_TIME', 10);
define('TATT_DAILY_REST', 11);
define('TATT_DAILY_LUNCH', 12);
define('TATT_DAILY_SMOKE', 13);
define('TATT_WORKDAY_1', 14);
define('TATT_WORKDAY_2', 15);
define('TATT_WEEKEND_1', 16);
define('TATT_WEEKEND_2', 17);

// Gender. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('GENDER_MALE', 1);
define('GENDER_FEMALE', 2);

// Reservation Status. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('RES_QUEUE', 1);
define('RES_RESERVED', 2);
define('RES_CONFIRMED_QUEUE', 3);
define('RES_CONFIRMED_RESERVED', 4);
define('RES_ADMITTED', 5);
define('RES_CANCELLED', 6);
define('RES_UNCONFIRMED', 7);
define('RES_UNCONFIRMED_QUEUE', 8);

// Report Graph. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('REPORT_GRAPH_VERTICAL', 1);
define('REPORT_GRAPH_HORIZONTAL', 2);

// Message Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('MESSAGE_EMAIL', 1);
define('MESSAGE_SMS', 2);

// Message Status. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('MESSAGE_STATUS_DRAFT', 1);
define('MESSAGE_STATUS_NEW', 2);
define('MESSAGE_STATUS_SENT', 3);
define('MESSAGE_STATUS_DELIVERED', 4);
define('MESSAGE_STATUS_MESSAGE_READ', 5);
define('MESSAGE_STATUS_NOT_DELIVERED', 6);
define('MESSAGE_STATUS_CANCELLED', 7);

// Order Status. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('ORDER_STATUS_NEW', 1);
define('ORDER_STATUS_CANCELLED', 2);
define('ORDER_STATUS_SENT', 3);
define('ORDER_STATUS_DELIVERED', 4);

// Delivery Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('DELIVERY_TYPE_EMAIL', 1);
define('DELIVERY_TYPE_MAIL_STANDARD', 2);
define('DELIVERY_TYPE_MAIL_EXPRESS', 3);
define('DELIVERY_TYPE_GIFTCARD', 4);
define('DELIVERY_TYPE_PRINT', 5);

// Subscription Invoicing Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('SUBSCRIPTION_INVOICING_TYPE_CURRENT_PERIOD', 1);
define('SUBSCRIPTION_INVOICING_TYPE_NEXT_PERIOD', 2);
define('SUBSCRIPTION_INVOICING_TYPE_PREVIOUS_PERIOD', 3);

// Invoice Delivery Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('INVOICE_DELIVERY_TYPE_AUTOMATIC', 1);
define('INVOICE_DELIVERY_TYPE_DO_NOT_SEND', 2);
define('INVOICE_DELIVERY_TYPE_POST', 3);
define('INVOICE_DELIVERY_TYPE_EMAIL', 4);
define('INVOICE_DELIVERY_TYPE_ELECTRONIC_INVOICE', 5);

// Reservation Application Status. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('RAPPL_STATUS_DRAFT', 1);
define('RAPPL_STATUS_SUBMITTED', 2);
define('RAPPL_STATUS_IN_PROGRESS', 3);
define('RAPPL_STATUS_APPROVED', 4);
define('RAPPL_STATUS_DECLINED', 5);

// Service Type. NOTE: The file is generated by update_constants.php script, DO NOT edit manually!
define('ST_CUSTOMER_ACCESS', 1);
define('ST_EMPLOYEE_ACCESS', 2);
define('ST_ACCESS_MODE_ALWAYS_OPEN', 3);
define('ST_LOCKERS_MASTER', 4);
define('ST_DOCUMENT_LOCKER', 5);
define('ST_KIOSK_MASTER', 7);
define('ST_GIVE_ONE_ACCESS', 8);

